### PR TITLE
Fix #105 click listeners

### LINKED ISSUE #105: click listeners do not work
The click events are never fired. If I put a transparent view in front of my youtube view, the click event is fired for that transparent view, but then that transparent view steals the click event from the youtube seekbar, play, fullscreen button etc. 

Any suggestions? 

```
youTubePlayerView.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                log.debug( "youTubePlayerView:MOTIONEVENT");
                // Get motion event type
                switch (event.getAction()) {
                    // This event is when user clicks down
                    case MotionEvent.ACTION_DOWN:
                        log.debug( "youTubePlayerView:ACTION_DOWN");
                        EventBus.getDefault().post(new VideoUIControlEvent("EXPAND_VIDEO"));
                        break;
                }
                return true;
            }

        });
```

 ```
       youTubePlayerView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                log.debug( "youTubePlayerView:setOnClickListener");
            }
        });
```

### PR DESCRIPTION
**Pull request by AbelTesfaye**
This pull requests fixes a bug that prevented users from registering onClick/onLongCLick/onTouch listeners on YouTubePlayerView

Test: YouTubePlayerViewClickTest.kt

Bug: #105

### CODE REVIEW

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt [hunk 1]
```diff
@@ -16,11 +17,40 @@ open class SixteenByNineFrameLayout: FrameLayout {
...
+     * the event from reaching the children.
+     * @param ev: The motion event being dispatched down the hierarchy.
+     * @return Return true to steal motion events from the children
+     * and have them dispatched to this ViewGroup through onTouchEvent()
+     */
+    override fun onInterceptTouchEvent(ev: MotionEvent): Boolean {
+
+        // Even though click and long click events are being called, the touch listener
+        // doesn't seem to work. So we need to register and use our own touch listener
+       val isTouchEventHandled = customOnTouchListener?.onTouch(rootView,ev)
```
Comment (PierfrancescoSoffritti) [inline core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: `val isTouchEventHandled = customOnTouchListener?.onTouch(rootView,ev) ?: false`

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt [hunk 2]
```diff
@@ -16,11 +17,40 @@ open class SixteenByNineFrameLayout: FrameLayout {
...
+
+        if(isTouchEventHandled == null || !isTouchEventHandled)
+            onTouchEvent(ev)
+
+        return super.onInterceptTouchEvent(ev)
+    }
+
+    override fun setOnTouchListener(listener: OnTouchListener?) {
+        customOnTouchListener = listener;
```
Comment (PierfrancescoSoffritti) [inline core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: Remove semicolon.

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt [hunk 3]
```diff
@@ -16,11 +17,40 @@ open class SixteenByNineFrameLayout: FrameLayout {
     constructor(context: Context, attrs: AttributeSet?) : this(context, attrs, 0)
     constructor(context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0) : super(context, attrs, defStyleAttr)
 
+    var customOnTouchListener: OnTouchListener? =null
```
Comment (PierfrancescoSoffritti) [inline core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: private. And add space between = and null.

`private var customOnTouchListener: OnTouchListener? = null`

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt [hunk 4]
```diff
@@ -16,11 +17,40 @@ open class SixteenByNineFrameLayout: FrameLayout {
...
     override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
         if (layoutParams.height == ViewGroup.LayoutParams.WRAP_CONTENT) {
             val sixteenNineHeight = View.MeasureSpec.makeMeasureSpec(View.MeasureSpec.getSize(widthMeasureSpec) * 9 / 16, View.MeasureSpec.EXACTLY)
             super.onMeasure(widthMeasureSpec, sixteenNineHeight)
         } else
             super.onMeasure(widthMeasureSpec, heightMeasureSpec)
     }
+
+    /**
+     * This method is usually used to intercept all touch screen motion events.
```
Comment (PierfrancescoSoffritti) [inline core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: This method is usually used to intercept touch events.

No need to add `@params` here, since we are overriding.

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt [hunk 5]
```diff
@@ -0,0 +1,81 @@
...
+
+@LargeTest
+class YouTubePlayerViewClickTest {
+
+    @Rule @JvmField
+    var activityRule = ActivityTestRule(TestActivity::class.java)
+
+    @Test
+    fun testSingleClickListener() {
+        onView(withId(R.id.youtube_player_view)).perform(click())
```
[the remark this answers is not in the document]
Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: So...the click test and longClick test use mockito now. But the touch listeners tests (swipeRight and swipeDown) need implementation detail (since they're not a test to just see if a method is called or not), i'm currently using the manual method for these tests. If there's a better way, please let me know so I can improve it.

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/helpers/MotionEventPrimitive.kt [hunk 6]
```diff
@@ -0,0 +1,21 @@
+package com.pierfrancescosoffritti.androidyoutubeplayer.core.helpers
+
+/**
+ * This class is needed to export MotionEvent attributes from Activity to the TestClasses.
+ * Using the MotionEvent directly is not possible since it get overwritten by internal
+ * code before it reaches the TestClass
+ *
+ * @constructor Creates an initialized MotionEvent
+ */
+class MotionEventPrimitive{
```
[the remark this answers is not in the document]
Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/helpers/MotionEventPrimitive.kt]: This class is no longer needed

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/helpers/MotionEventPrimitive.kt [hunk 7]
```diff
@@ -0,0 +1,21 @@
+package com.pierfrancescosoffritti.androidyoutubeplayer.core.helpers
+
+/**
+ * This class is needed to export MotionEvent attributes from Activity to the TestClasses.
```
[the remark this answers is not in the document]
Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/helpers/MotionEventPrimitive.kt]: Since all motionEvents point to the same object, they all had the value that was set last. So, I used this class to transfer the values to a new instance.

I found a better way to do that: `MotionEvent.obtain()`

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/testActivity/TestActivity.kt [hunk 8]
```diff
@@ -13,6 +15,31 @@ class TestActivity : AppCompatActivity() {
...
+                            motionEvent.action
+                    )
+            )
+            false
+        }
+
         lifecycle.addObserver(youTubePlayerView)
     }
+
+    companion object {
```
[the remark this answers is not in the document]
Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/testActivity/TestActivity.kt]: ditto

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt (hunk 1 above)
Comment (AbelTesfaye) [reply core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: fixed

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt (hunk 2 above)
Comment (AbelTesfaye) [reply core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: fixed

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt (hunk 3 above)
Comment (AbelTesfaye) [reply core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: fixed

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt (hunk 4 above)
Comment (AbelTesfaye) [reply core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: ok

**Comment by AbelTesfaye** [comment]
@PierfrancescoSoffritti I'm really sorry for the noobie mistakes i'm making, I'm super new to testing, so I don't really know what is the best way to do stuff. With every correction you give me, I'm improving and I just want to say thank you for that!

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt [hunk 9]
```diff
@@ -16,11 +17,34 @@ open class SixteenByNineFrameLayout: FrameLayout {
...
         } else
             super.onMeasure(widthMeasureSpec, heightMeasureSpec)
     }
+
+    /**
+     * This method is usually used to intercept events.
+     * @return Return true to steal motion events from the children
+     * and have them dispatched to this ViewGroup through onTouchEvent()
+     */
+    override fun onInterceptTouchEvent(ev: MotionEvent): Boolean {
```
Comment (PierfrancescoSoffritti) [inline core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: I think the description of why we are overriding this method got lost?

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+    val clickTestViewId = R.id.youtube_player_view
+
+    @Before
+    fun setup() {
+        testActivity = activityRule.getActivity()
+        youTubePlayerView = testActivity!!.findViewById(R.id.youtube_player_view)
+    }
+
+    @Test
+    fun testSingleClickListener() {
```
[the remark this answers is not in the document]
Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: I definitely agree with this.

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt [hunk 11]
```diff
@@ -0,0 +1,116 @@
...
+
+        youTubePlayerView!!.setOnLongClickListener(mockLongClickListener)
+        onView(withId(clickTestViewId)).perform(longClick())
+
+        verify(mockLongClickListener).onLongClick(youTubePlayerView)
+    }
+
+    @Test
+    fun testTouchSwipeDownListener() {
+        val touchEventQueue: Queue<MotionEvent> = LinkedList()
```
[the remark this answers is not in the document]
Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: Needs explicit type to be set or it wont compile

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt [hunk 12]
```diff
@@ -0,0 +1,116 @@
...
+            if (actualEventAction!!.action == MotionEvent.ACTION_DOWN) {
+                prevMotionEvent = actualEventAction
+            } else if (actualEventAction.action == MotionEvent.ACTION_MOVE) {
+                assertEquals(prevMotionEvent!!.x, actualEventAction.x)
+                assertTrue(prevMotionEvent.y < actualEventAction.y)
+
+                prevMotionEvent = actualEventAction
+            }
+        }
+        assertNotNull(prevMotionEvent)
```
[the remark this answers is not in the document]
Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: if queue is empty (touch fails) then `prevMotionEvent` will remain null

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt (hunk 9 above)
Comment (AbelTesfaye) [reply core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: lol, I thought you wanted it that way: https://github.com/PierfrancescoSoffritti/android-youtube-player/pull/521#discussion_r379856256

Will bring the description back.

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt (hunk 11 above)
[the remark this answers is not in the document]
Comment (PierfrancescoSoffritti) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: Sorry, I forgot that part. You can do this:

`val touchEventQueue = LinkedList<MotionEvent>()`

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt (hunk 9 above)
Comment (PierfrancescoSoffritti) [reply core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: Ah sorry, with that comment I meant "rephrase the first line" :)

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt (hunk 12 above)
[the remark this answers is not in the document]
Comment (PierfrancescoSoffritti) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: It would be better to find a more explicit way of testing that.

Maybe set a boolean to true once the touch happens and then assert that?
Otherwise mockito has a `spy` method that you can use to create mocks and maintain your implementation logic. I think you could: create the listener, create a spy object of it and then set the spy as the listener. Like:

```
val listener = TouchListener { // impl }
val spyListener = spy(listener)
view.addListener(spyListener)
verify(spyListener).onTouch()
```

This should be possible, correct me if I'm wrong though.

[the remark this answers is not in the document]
Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: I tried a lot of ways to make the `spy()` way work. But it doesn't seem to work on listeners. So, i'm using the boolean way instead

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt [hunk 13]
```diff
@@ -0,0 +1,130 @@
...
+    @Rule
+    @JvmField
+    val activityRule = ActivityTestRule(TestActivity::class.java)
+    private lateinit var testActivity: Activity
+
+    private lateinit var youTubePlayerView: YouTubePlayerView
+
+    private val clickTestViewId = R.id.youtube_player_view
+
+    @Before
```
Comment (PierfrancescoSoffritti) [inline core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: Group like this:

private lateinit var testActivity: Activity
private lateinit var youTubePlayerView: YouTubePlayerView

@Rule
@JvmField
val activityRule = ActivityTestRule(TestActivity::class.java)

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt [hunk 14]
```diff
@@ -0,0 +1,130 @@
...
+    }
+
+    @Test
+    fun testSingleClickListener() {
+        // Prepare
+        val mockClickListener = mock(View.OnClickListener::class.java)
+        youTubePlayerView.setOnClickListener(mockClickListener)
+
+        // Act
+        onView(withId(clickTestViewId)).perform(click())
```
Comment (PierfrancescoSoffritti) [inline core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: No need to store `clickTestViewId` in a variable, do `R.id.youtube_player_view` in each test.

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt [hunk 15]
```diff
@@ -16,11 +17,40 @@ open class SixteenByNineFrameLayout: FrameLayout {
...
+
+    /**
+     * This method is usually used to intercept events.
+     * This allows to watch events as they are dispatched to the children,
+     * and take ownership of the current gesture at any point.
+     *
+     * We're using it to call onTouchEvent() without stopping
+     * the event from reaching the children.
+     * 
+     * @return Return true to steal motion events from the children
```
Comment (PierfrancescoSoffritti) [inline core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: Same as for @param, no need to have @return here, it is already defined in the super class.

File: core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt [hunk 16]
```diff
@@ -16,11 +17,40 @@ open class SixteenByNineFrameLayout: FrameLayout {
...
+     * and have them dispatched to this ViewGroup through onTouchEvent()
+     */
+    override fun onInterceptTouchEvent(ev: MotionEvent): Boolean {
+
+        // Even though click and long click events are being called, the touch listener
+        // doesn't seem to work. So we need to register and use our own touch listener
+       val isTouchEventHandled = customOnTouchListener?.onTouch(rootView,ev) ?: false
+
+        if(isTouchEventHandled == null || !isTouchEventHandled)
```
Comment (PierfrancescoSoffritti) [inline core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/SixteenByNineFrameLayout.kt]: `isTouchEventHandled` is not nullable anymore, you can remove the check for null in the if.

File: core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt [hunk 17]
```diff
@@ -0,0 +1,128 @@
...
+            false
+        }
+
+        // Act
+        onView(withId(R.id.youtube_player_view)).perform(swipeDown())
+
+        // Assert
+        assertTrue(onTouchWorks)
+
+        lateinit var prevMotionEvent: MotionEvent
```
Comment (PierfrancescoSoffritti) [inline core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: I'm confused, don't you get a compilation error using `lateinit` here?

Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: nope, it works

Comment (PierfrancescoSoffritti) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: Interesting. Let's make it nullable instead:
`var prevMotionEvent: MotionEvent? = null`

Comment (AbelTesfaye) [reply core/src/androidTest/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/YouTubePlayerViewClickTest.kt]: sure thing!

**Comment by AbelTesfaye** [comment]
Forgot to squash changes :sweat_smile:

**Comment by PierfrancescoSoffritti** [comment]
Just wait for Travis to finish, then we can squash and merge

**Comment by AbelTesfaye** [comment]
This is good for merge :tada:

**Comment by Raghuramchowdary-tech** [comment]
have these changes ever got released?

**Comment by peterslight** [comment]
@PierfrancescoSoffritti hey man, was this PR merged and released? I cannot seem to override touch events in v11.0.1, also cannot find the changes in the v11.0.1

**Comment by PierfrancescoSoffritti** [comment]
Hey, I didn't have time to properly verify these changes where ok, so i had to revert them for now. Couldn't afford them breaking something and having to spend more time fixing an urgent bug in the lib.
